### ISSUE TITLE
typo in font file

### ISSUE THREAD

**Issue by xunil-cloud** [geom3trik/tuix#1]
Hi, I just tried to build the example on Linux and got an error in [application.rs](https://github.com/geom3trik/tuix/blob/0013337216d09038b997b241654bb9f6fb96928f/src/application.rs#L48). It seems that `resources/entypo.ttf` should be renamed into `resources/Entypo.ttf`.

**Comment by geom3trik** [comment]
Hi, good spot! I code on Windows and I forgot that linux is case sensitive for file names. I shall fix it now.

**Comment by xunil-cloud** [comment]
Ah! Thanks.

**Comment by geom3trik** [comment]
Okay that should be fixed now. I've also fixed the examples that weren't working. You'll have to forgive me, I use the examples as a way to test features so some of them are quite random.

See if that fixes your issue.

**Comment by xunil-cloud** [comment]
Yep, it works now.

**Comment by geom3trik** [comment]
Excellent :) please report any more bugs you find, I have no way to test on linux currently. Closing this issue now.
