### ISSUE TITLE
Bundling assets with release build

### ISSUE THREAD

**Issue by aimerib** [geom3trik/tuix#14]
First of all, I can't express strongly enough how much this project excites me. I've been looking around the GUI libs in rust, and while quite a few of them show great potential, Tuix is the first library that seems to make simple desktop apps possible without the cognitive overhead of other libraries.
Since I have no production goals with the things I'm building, I don't mind that this is only early stages of this library.

I do have a question regarding assets required when building my application. It seems like as of now, when I need to load a stylesheet or an image, my application needs to load them from the file system. When creating a release build, I couldn't see any way to bundle those assets with the build. My assumption is that this is because of how the image and css crates work, but are there any plans to make assets and build bundled together?
For my specific immediate needs this isn't really an issue, as I can keep everything in the same folder without an issue, but I am having a hard time thinking how I could distribute my application should I ever need to. I certainly could just zip everything and ship a zip file, or I could try to package it and use the default app settings folder in whatever native way the OS does that (like a folder in ProgramData for window, or $XDG_CONFIG_HOME on ubuntu), but if I am using filesystem paths inside the source code this seems like it might be harder to get consistently right.

This is less of an actual issue, and more of a question about future plans.

Thank you so much for your hard work on this!

**Comment by geom3trik** [comment]
Hello, and thank you for your interest in tuix! So for stylesheets you can define them within a rust file using a constant, something like: `const STYLE: &str = r#"css goes here"#` and then use `state.add_theme(STYLE)`. You can do a similar thing and still have your stylesheets in separate files but then use the `include_str!()` macro and this will package that files contents into the binary. However, I should note that you lose the ability to hot reload the style properties if you do it this way. For images I haven't got support fully working yet but when I do I imagine you should be able to do the same thing that I do with the default fonts which is to use the `include_bytes!()` macro to package the raw data into the binary. For future plans I'm hoping to have a more robust resource manager (that's the main reason I don't have support for images yet) and perhaps some of this can be done for you by the resource manager once the app you create is ready to be distributed.

Out of curiosity, how did you find out about tuix?

**Comment by aimerib** [comment]
Oh, that is really good news! I wonder if a similar process would work for images but converting them to base64 first, and just using the base64 version of the string in a constant as well. I will have to test that theory before I speculate any more, but if that does work, having an assets.rs file could potentially work as a source of truth for now.
A resources manager would be most welcome, so I'll keep an eye out for that.

I was browsing the gui section of lib.rs. I've been building a text-adventure (a la Zork) that is quickly turning more into an engine that just a single game. As a consequence, managing the game files that will actually contain the game data becomes a little unwieldy to do by hand (I'm using yaml for the game files). What I had in mind was to have a simple editor that could keep track of which files currently exist and help me create more, that way I separate creating the engine from creating the actual game.
The game itself is meant to be ran on the terminal (I'm using TUI for that part), but for editing the game files I really wanted something a little bit more visual, but a lot of the other libraries tend to do either too much, or not enough. There were a couple of other libraries that I considered, and up until yesterday I was convinced I'd end up having to use druid which looks really promising too, but following their documentation was a little daunting. Tuix was easy to follow, and I had a small simple app for testing input and output in just under an hour, which for a library I never used was pretty cool. For comparison, Tui which is a pretty decent and documented library, took me a good part of two days to figure out layout and positioning.

I do hope that more people come across Tuix because this library has a lot of potential! Again, thank you for taking the time to respond, and for the suggestion above!

**Comment by geom3trik** [comment]
That's good to hear that you managed to get something working so quickly. One of the goals for tuix is to have a gui lib that you can just use straight out of the box, no need to add extra dependencies or provide your own windowing/rendering. As you've seen tuix is still in an early stage of development with lots of things that don't quite work right just yet. This is why I haven't really advertised tuix yet except to a small group of people. Hopefully tuix can meet your needs, and if you find any problems then feel free to raise an issue, or if you have discord then there is a discord server (link at the top of the readme).

**Comment by aimerib** [comment]
Thank you! I missed the discord link on my first pass, so if I have more questions about general use or direction I'll pop there.

Also, I completely understand that the library is still in very early stages. It seems like it does pretty much most of the things I need, since the ui part will be largely input boxes and buttons, nothing fancy. The core of the logic will be mostly backend related, so my needs are minimal.
I'll go ahead and close this issue, and open new ones if I find actual bugs. Once again, thank you!
