### ISSUE TITLE
New layout system

### ISSUE THREAD

**Issue by geom3trik** [geom3trik/tuix#16]
New layout system based on: https://subformapp.com/articles/why-not-flexbox/

## Overview:
- All elements have a horizontal and vertical axis, each of which consists of space before, size, and space after.
- Elements either control their own position (“self-directed”, akin to CSS absolute positioning) or are positioned by their parent (parent-directed).
- Parents can position their parent-directed children in a vertical stack, horizontal stack, or grid.
- The same units—pixels, percentages (of the parent size), and stretch (akin to flex, proportionally dividing up available space)—are used everywhere, with minimum and maximum constraints as part of the unit.

### Element
- [x] parent-directed
- [x] self-directed
- [x] `space_before`, `space_after`, and `size` for main and cross axes.
- [x] pixel units
- [x] percentage units
- [x] stretch units
- [x] min/max on units

### Stack
- [x] horizontal stack
- [x] vertical stack
- [x] `space_before_first`, `space_between`, `space_after_last`
- [x] element override for `space_before` and `space_after`

### Stack Wrapping
- [ ] wrapping
- [ ] element override for `space_before` and `space_after` on cross axis (wrap axis)
- [ ] `space_before_first` and `space_after_last` for wrapped elements
- [ ] `space_between` for cross axis (wrap axis)

### Grid
- [x] grid rows
- [x] grid cols
- [x] grid item row index and row span
- [x] grid item col index and col span
- [x] grid `space_before_first` and `space_after_last`
- [ ] element override for `space_before` and `space_after` (does this even make sense?)

**Comment by dumblob** [comment]
The layout system seems interesting - do you have any good tuix examples using this newer layout?

**Comment by geom3trik** [comment]
> The layout system seems interesting - do you have any good tuix examples using this newer layout?

So the 'new' layout system was moved to its own crate called morphorm https://github.com/geom3trik/morphorm. There are some examples in there but I keep meaning to add more. Tuix now uses this crate for layout so all of the examples use this layout system (make sure to use the `reactive` branch of tuix because main is very out of date). I am yet to write some good documentation for it but there's an overview of the system here: https://geom3trik.github.io/tuix-book/layout/stack_overview.html, but `child-between` has been replaced with `col-between` and `row-between`. The most complex example which makes use of it is an editor I'm working on which is in the `color-picker` branch. It's very WIP but I think it gives a good example of the kind of layouts which are possible.

**Comment by dumblob** [comment]
>...`color-picker`...

Perfect, this might be exactly what I was looking for (I want to present this system to others, so I wanted to see something more complex but still readable :wink:)!

**Comment by geom3trik** [comment]
Ah cool! 😀 Well I hope it's readable, but it's still very work in progress and I haven't made much effort to comment anything. You'll find the editor in an example called `editor.rs`. At the moment it's just one big file but eventually I'll split it out to make it easier to read. The layout code is split between 'inline' properties on the widgets when building them and 'css' properties which are at the top of the file. Some layout properties are set within the widgets themselves. For example, the `LengthBox` widget has a `col-between` of 10 px to add some space between the slider, textbox, and dropdown, but eventually I'll make it configurable. Feel free to ask me any questions about the layout system, either here or on Discord if you like (the link to join is in the readme). If you find any bugs with layout in particular it's probably best to raise an issue on the Morphorm crate.
